"""
Memory Engine Enums.

Type-safe classification values for the Memory subsystem.
Using Enums instead of raw strings prevents typos and enables IDE autocompletion.
"""

from enum import Enum


class MemoryType(str, Enum):
    """
    Classification of a memory entry by its semantic nature.

    EPISODE: A conversation turn or action sequence (episodic memory).
    FACT:    An extracted piece of knowledge (semantic memory).
    PROFILE: User preferences, habits, personal info.
    """

    EPISODE = "episode"
    FACT = "fact"
    PROFILE = "profile"


class MemorySource(str, Enum):
    """
    Origin of a memory entry — who or what created it.

    USER:           Directly from user input.
    AGENT:          Generated by an agent during task execution.
    CONSOLIDATION:  Extracted by the consolidation pipeline.
    SYSTEM:         Created by system processes (e.g., boot events).
    """

    USER = "user"
    AGENT = "agent"
    CONSOLIDATION = "consolidation"
    SYSTEM = "system"


class SourceTier(str, Enum):
    """
    Which memory tier a search result originated from.

    SHORT_TERM: In-memory conversation buffer (recent turns).
    LONG_TERM:  SQLite-based persistent storage (episodes, facts, profile).
    VECTOR:     Vector similarity search (embeddings).
    """

    SHORT_TERM = "short_term"
    LONG_TERM = "long_term"
    VECTOR = "vector"
