# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('configs', 'configs'),
        ('.env', '.'),
    ],
    hiddenimports=[
        'google.generativeai',
        'google.ai.generativelanguage',
        'openai',
        'httpx',
        'requests',
        'core',
        'core.cognition',
        'core.goals',
        'core.knowledge',
        'core.runtime',
        'core.vision',
        'core.desktop',
        'core.browser',
        'core.telemetry',
        'core.events',
        'core.utils',
        'core.utils.paths',
        'app',
        'app.bootstrap',
        'app.services',
        'app.viewmodels',
        'app.ui',
        'app.ui.chat',
        'app.ui.notification',
        'app.ui.widgets',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Eric',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
